USE QLQCP;
GO

CREATE INDEX IX_DOAN_Gia ON DOAN(Gia);
CREATE INDEX IX_DOUONG_Gia ON DOUONG(Gia);
CREATE INDEX IX_KHACHHANG_SDT ON KHACHHANG(SDT);
CREATE INDEX IX_HOADON_NgayLap ON HOADON(NgayLap);
CREATE INDEX IX_HOADON_MaKH ON HOADON(MaKH);
CREATE INDEX IX_CHITIETHOADON_MaDoAn ON CHITIETHOADON(MaDoAn);
CREATE INDEX IX_CHITIETHOADON_MaDoUong ON CHITIETHOADON(MaDoUong);
CREATE INDEX IX_CHITIETHOADON_SoLuong ON CHITIETHOADON(SoLuong);
GO