USE QLQCP;
GO


CREATE VIEW HOADONCHITIET AS
SELECT
    HD.MaHoaDon AS MaHoaDon,
    KH.TenKH AS TenKhachHang,
    HD.NgayLap AS NgayLap,
    COALESCE(DA.TenDoAn, DU.TenDoUong) AS TenMon,
    CTHD.SoLuong AS SoLuong,
    ISNULL (DA.Gia, DU.Gia) AS DonGia,
    (CTHD.SoLuong * ISNULL (DA.Gia, DU.Gia)) AS ThanhTien
FROM HOADON HD
INNER JOIN CHITIETHOADON CTHD ON CTHD.MaHoaDon = HD.MaHoaDon
INNER JOIN KHACHHANG KH ON HD.MaKH = KH.MaKH
LEFT JOIN DOAN DA ON CTHD.MaDoAn = DA.MaDoAn
LEFT JOIN DOUONG DU ON CTHD.MaDoUong = DU.MaDoUong;
GO

SELECT * FROM HOADONCHITIET
WHERE MaHoaDon = 1;
GO