USE master;
GO

USE QLQCP;
GO

CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'ThisIsPassword';

CREATE CERTIFICATE CaPheChoi
WITH SUBJECT = 'Nhan vien ngon hon ca phe';

CREATE DATABASE ENCRYPTION KEY
WITH ALGORITHM = AES_256
ENCRYPTION BY SERVER CERTIFICATE CaPheChoi;

ALTER DATABASE QLQCP
SET ENCRYPTION ON;
