CREATE DATABASE QLQCP;
GO

USE QLQCP;
GO

CREATE TABLE DOAN(
    MaDoAn INT PRIMARY KEY,
    TenDoAn NVARCHAR(100) NOT NULL,
    Gia DECIMAL(10, 2) NOT NULL,
);

CREATE TABLE DOUONG(
    MaDoUong INT PRIMARY KEY,
    TenDoUong NVARCHAR(100) NOT NULL,
    Gia DECIMAL(10, 2) NOT NULL 
);

CREATE TABLE KHACHHANG(
    MaKH INT PRIMARY KEY,
    TenKH NVARCHAR(100) NOT NULL,
    SDT NVARCHAR(15) NOT NULL
);

CREATE TABLE HOADON(
    MaHoaDon INT PRIMARY KEY,
    NgayLap DATETIME NOT NULL,
    MaKH INT
);

CREATE TABLE CHITIETHOADON(
    MaHoaDon INT,
    MaDoAn INT NULL,
    MaDoUong INT NULL,
    SoLuong INT NOT NULL
);

ALTER TABLE HOADON
ADD CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH);
GO

ALTER TABLE CHITIETHOADON
ADD CONSTRAINT FK_CHITIETHOADON_HOADON FOREIGN KEY (MaHoaDon) REFERENCES HOADON(MaHoaDon);  
ALTER TABLE CHITIETHOADON
ADD CONSTRAINT FK_CHITIETHOADON_DOAN FOREIGN KEY (MaDoAn) REFERENCES DOAN(MaDoAn);  
ALTER TABLE CHITIETHOADON
ADD CONSTRAINT FK_CHITIETHOADON_DOUONG FOREIGN KEY (MaDoUong) REFERENCES DOUONG(MaDoUong);
GO

INSERT INTO DOAN (MaDoAn, TenDoAn, Gia) VALUES
(1, N'Khô gà', 25000),
(2, N'Khô bò', 25000),
(3, N'Nem chua rán', 36000),
(4, N'Ngô cay', 15000),
(5, N'Hướng dương', 15000);

INSERT INTO DOUONG (MaDoUong, TenDoUong, Gia) VALUES
(1, N'Cà phê đen', 20000),
(2, N'Cà phê sữa', 20000),
(3, N'Bạc xỉu', 28000),
(4, N'Cà phê muối', 28000),
(5, N'Americano', 25000),
(6, N'Capuchino', 32000),
(7, N'Caramel Macchiato', 35000),
(8, N'Matcha latte', 30000),
(9, N'Matcha macchiato', 35000),
(10, N'Cacao latte', 30000),
(11, N'Trà đào cam sả', 32000),
(12, N'Hồng trà việt quất', 30000),
(13, N'Trà chanh nha đam', 20000);