USE QLQCP;
GO

CREATE ROLE QUANLY;
CREATE ROLE NHANVIEN;
CREATE ROLE KHACHHANG;
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON DOAN TO QUANLY;
GRANT SELECT, INSERT, UPDATE, DELETE ON DOUONG TO QUANLY;
GRANT SELECT, INSERT, UPDATE, DELETE ON KHACHHANG TO QUANLY;
GRANT SELECT, INSERT, UPDATE, DELETE ON HOADON TO QUANLY;
GRANT SELECT, INSERT, UPDATE, DELETE ON CHITIETHOADON TO QUANLY;
GRANT EXECUTE ON THEMDOAN TO QUANLY;
GRANT EXECUTE ON THEMDOUONG TO QUANLY;
GRANT EXECUTE ON THEMKHACHHANG TO QUANLY;
GRANT EXECUTE ON THEMHOADON TO QUANLY;
GRANT EXECUTE ON THEMCHITIETHOADON TO QUANLY;
GRANT EXECUTE ON SUADOAN TO QUANLY;
GRANT EXECUTE ON SUADOUONG TO QUANLY;
GRANT EXECUTE ON SUAKHACHHANG TO QUANLY;
GRANT EXECUTE ON SUAHOADON TO QUANLY;
GRANT EXECUTE ON SUACHITIETHOADON TO QUANLY;
GRANT EXECUTE ON XOADOAN TO QUANLY;
GRANT EXECUTE ON XOADOUONG TO QUANLY;
GRANT EXECUTE ON XOAKHACHHANG TO QUANLY;
GRANT EXECUTE ON XOAHOADON TO QUANLY;
GRANT EXECUTE ON XOACHITIETHOADON TO QUANLY;
GO

GRANT SELECT, INSERT ON DOAN TO NHANVIEN;
GRANT SELECT, INSERT ON DOUONG TO NHANVIEN;
GRANT SELECT, INSERT ON KHACHHANG TO NHANVIEN;
GRANT SELECT, INSERT ON HOADON TO NHANVIEN;
GRANT SELECT, INSERT ON CHITIETHOADON TO NHANVIEN;
GRANT EXECUTE ON THEMDOAN TO NHANVIEN;
GRANT EXECUTE ON THEMDOUONG TO NHANVIEN;
GRANT EXECUTE ON THEMKHACHHANG TO NHANVIEN;
GRANT EXECUTE ON THEMHOADON TO NHANVIEN;
GRANT EXECUTE ON THEMCHITIETHOADON TO NHANVIEN;
GO

GRANT SELECT ON DOAN TO KHACHHANG;
GRANT SELECT ON DOUONG TO KHACHHANG;
GO
